# Generated by Django 2.2.28 on 2023-03-23 15:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(default='Description', max_length=2048)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=8, validators=[django.core.validators.MaxValueValidator(90.0), django.core.validators.MinValueValidator(-90.0)])),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MaxValueValidator(180.0), django.core.validators.MinValueValidator(-180.0)])),
                ('rent_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rent_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(1.0)])),
                ('reviews_no', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='accommodation_images')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=8, validators=[django.core.validators.MaxValueValidator(90.0), django.core.validators.MinValueValidator(-90.0)])),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MaxValueValidator(180.0), django.core.validators.MinValueValidator(-180.0)])),
                ('description', models.CharField(default='Description', max_length=2048)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='university_images')),
                ('website', models.URLField(blank=True)),
                ('synopsis', models.CharField(default='Synopsis', max_length=1024)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_student', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 3, 23, 15, 44, 29, 242021, tzinfo=utc))),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm_detective_app.Accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm_detective_app.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm_detective_app.University'),
        ),
        migrations.AlterUniqueTogether(
            name='accommodation',
            unique_together={('university', 'name')},
        ),
    ]
