# Generated by Django 2.2.28 on 2023-03-09 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.CharField(default='Description', max_length=2048),
        ),
        migrations.AddField(
            model_name='university',
            name='picture',
            field=models.ImageField(blank=True, upload_to='university_images'),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, validators=[django.core.validators.MaxValueValidator(90.0), django.core.validators.MinValueValidator(-90.0)]),
        ),
        migrations.AlterField(
            model_name='university',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MaxValueValidator(180.0), django.core.validators.MinValueValidator(-180.0)]),
        ),
    ]
