# Generated by Django 2.2.28 on 2023-03-24 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0002_auto_20230324_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 12, 57, 11, 935080, tzinfo=utc)),
        ),
    ]
