# Generated by Django 2.2.28 on 2023-03-16 01:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0003_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='university_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_student',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm_detective_app.Accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm_detective_app.UserProfile')),
            ],
        ),
    ]
