# Generated by Django 2.2.28 on 2023-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0004_reviews'),
        ('dorm_detective_app', '0002_auto_20230315_2051'),
    ]

    operations = [
    ]
