# Generated by Django 2.2.28 on 2023-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0005_merge_20230316_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(default='a', unique=True),
        ),
    ]
