# Generated by Django 2.2.28 on 2023-03-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0006_university_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
