# Generated by Django 2.2.28 on 2023-03-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0006_university_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
