# Generated by Django 2.2.28 on 2023-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0007_auto_20230321_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
    ]
