# Generated by Django 2.2.28 on 2023-03-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0007_auto_20230320_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
