# Generated by Django 2.2.28 on 2023-03-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0009_remove_accommodation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
    ]
