# Generated by Django 2.2.28 on 2023-03-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0010_accommodation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='slug',
            field=models.SlugField(),
        ),
    ]
