# Generated by Django 2.2.28 on 2023-03-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0011_auto_20230320_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
