# Generated by Django 2.2.28 on 2023-03-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0008_accommodation_slug'),
        ('dorm_detective_app', '0012_auto_20230320_2302'),
    ]

    operations = [
    ]
