# Generated by Django 2.2.28 on 2023-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0013_merge_20230321_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='synopsis',
            field=models.CharField(default='Synopsis', max_length=1024),
        ),
    ]
