# Generated by Django 2.2.28 on 2023-03-23 12:49

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0014_university_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='address',
            field=django_google_maps.fields.AddressField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
