# Generated by Django 2.2.28 on 2023-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_detective_app', '0014_university_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='email_domain',
            field=models.CharField(default='example.com', max_length=128),
        ),
    ]
